name: 'Purge cache for CloudFront'
description: 'purge article cache'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS ACCESS KEY ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS SECRET ACCESS KEY'
    required: true
  AWS_REGION:
    description: 'AWS REGION'
    required: false
    default: 'ap-northeast-1'
  AWS_PURGE_PATHS:
    description: 'will purge paths'
    required: false
    default: '/*'
  S3_BUCKET_NAME:
    description: 'AWS S3 BUCKET NAME'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
